# **Разведочный анализ по датасету IMDb Movies: 5000 фильмов с наибольшим рейтингом. Часть 3: Фильтрация, срезы, группировка**

![](https://adabul.com/wp-content/uploads/2020/04/diziler-360x240.jpg)

## 1. Описание датасета и задания

Представлен датасет с данными о 5000 фильмах, имеющих наибольший рейтинг на сайте IMDb (датасет выложен на платформе [Kaggle](https://www.kaggle.com/datasets/totoro29/imdb-movies)).

***Информация, содержащаяся в датасете:***
1.   Ссылка на постер фильма (poster).
2.   Наименование фильма (title).
3.   Класс фильма по рейтингу the British Board of Film Classification (BBFC) (certificate).
4.   Продолжительность фильма (runtime).
5.   Жанр фильма (genre).
6.   Рейтинг фильма на платформе IMBD (rating).
7.   Описание сюжета фильма (about).
8.   Кинорежиссер фильма (director).
9.   Актеры-звезды фильма (stars).
10.  Количество проголосовавших за фильм (votes).
11.  Доход с фильма (gross_earn).

***Задача:***
провести разведочный анализ данных, найти взаимосвязи и сформулировать выводы.

**В части 3 задания необходимо:**
1.   Найти подходящий к просмотру фильм с помощью фильтрации.
2.   Отобрать фильмы с помощью срезов.
3.   Выбрать показатели описательной статистики по отфильтрованным фильмам с помощью срезов.
4.   Отобрать фильмы с помощью продвинутой фильтрации.
5.   Отфильтровать колонки с помощью продвинутой фильтрации.
6.   Вывести информацию, сгруппированную по определенным признакам.

****Задания со звездочкой факультативные (дополнительные)***

## 2. Загрузка датасета

Импортируйте модуль files для подгрузки датасета с ПК

In [1]:
from google.colab import files

Загрузите файл movies_clean.csv (сохранен по итогу выполнения предыдущего задания) с помощью files.upload()

In [2]:
files.upload()

Saving movies_clean.csv to movies_clean.csv


{'movies_clean.csv': b',poster,title,certificate,runtime,genre,rating,about,director,stars,votes,gross_earn,runtime_clear,gross_earn_clear\n0,https://m.media-amazon.com/images/S/sash/4FyxwxECzL-U1J8.png,The Shawshank Redemption,15,142 min,Drama,9.3,"Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",Frank Darabont,"(\'Tim Robbins\',), (\'Morgan Freeman\',), (\'Bob Gunton\',), (\'William Sadler\',)","26,26,905",$28.34M,142,28.34\n1,https://m.media-amazon.com/images/S/sash/4FyxwxECzL-U1J8.png,Hababam Sinifi,12A,87 min,"Comedy, Drama",9.2,"Lazy, uneducated students share a very close bond. They live together in the dormitory, where they plan their latest pranks. When a new headmaster arrives, the students naturally try to overthrow him. A comic war of nitwits follows.",Ertem Egilmez,"(\'Kemal Sunal\',), (\'M\xc3\xbcnir \xc3\x96zkul\',), (\'Halit Ak\xc3\xa7atepe\',), (\'Tarik Akan\',)","40,492",,87,\n2,https://m.media-ama

## 3. Подгрузка данных в питон и начало работы с ними

Импортируйте библиотеку pandas и присвойте ей короткое название pd

In [3]:
import pandas as pd

Откройте датасет movies_clean.csv и сохраните его в переменную dataset

In [4]:
dataset = pd.read_csv('movies_clean.csv')

Проведите обзор таблицы с помощью метода head()

In [5]:
dataset.head()

Unnamed: 0                                             poster  \
0           0  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1           1  https://m.media-amazon.com/images/S/sash/4Fyxw...   
2           2  https://m.media-amazon.com/images/S/sash/4Fyxw...   
3           3  https://m.media-amazon.com/images/S/sash/4Fyxw...   
4           4  https://m.media-amazon.com/images/S/sash/4Fyxw...   

                      title certificate  runtime                      genre  \
0  The Shawshank Redemption          15  142 min                      Drama   
1            Hababam Sinifi         12A   87 min              Comedy, Drama   
2             The Godfather           X  175 min               Crime, Drama   
3    The Godfather: Part II           X  202 min               Crime, Drama   
4          Schindler's List          15  195 min  Biography, Drama, History   

   rating                                              about  \
0     9.3  Two imprisoned men bond over a number of years...   
1     9.2  Lazy, uneducated students share a very close b...   
2     9.2  The aging patriarch of an organized crime dyna...   
3     9.0  The early life and career of Vito Corleone in ...   
4     9.0  In German-occupied Poland during World War II,...   

               director                                              stars  \
0        Frank Darabont  ('Tim Robbins',), ('Morgan Freeman',), ('Bob G...   
1         Ertem Egilmez  ('Kemal Sunal',), ('Münir Özkul',), ('Halit Ak...   
2  Francis Ford Coppola  ('Marlon Brando',), ('Al Pacino',), ('James Ca...   
3  Francis Ford Coppola  ('Al Pacino',), ('Robert De Niro',), ('Robert ...   
4      Steven Spielberg  ('Liam Neeson',), ('Ralph Fiennes',), ('Ben Ki...   

       votes gross_earn  runtime_clear  gross_earn_clear  
0  26,26,905    $28.34M            142             28.34  
1     40,492        NaN             87               NaN  
2  18,19,641   $134.97M            175            134.97  
3  12,49,182    $57.30M            202             57.30  
4  13,33,407    $96.90M            195             96.90

Удалите столбец 'Unnamed: 0' как ненужный с помощью метода drop(), передав в него параметры columns и inplace=True

In [6]:
dataset.drop(columns='Unnamed: 0', inplace=True)

## 4. Оценка размеров датасета

Оцените размеры датасета с помощью атрибута shape

In [7]:
dataset.shape

(4970, 13)

Выведите информацию о датасете с помощью метода info()

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4970 entries, 0 to 4969
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   poster            4970 non-null   object 
 1   title             4970 non-null   object 
 2   certificate       4970 non-null   object 
 3   runtime           4970 non-null   object 
 4   genre             4970 non-null   object 
 5   rating            4970 non-null   float64
 6   about             4956 non-null   object 
 7   director          4970 non-null   object 
 8   stars             4970 non-null   object 
 9   votes             4970 non-null   object 
 10  gross_earn        4574 non-null   object 
 11  runtime_clear     4970 non-null   int64  
 12  gross_earn_clear  4574 non-null   float64
dtypes: float64(2), int64(1), object(10)
memory usage: 504.9+ KB


## 5. Фильтрация

### *5.1. Выбираем, что посмотреть с племянником 10 лет - фанатом "Jurassic Park"*

**Описание:** Вас попросили присмотреть за племянником 10 лет. Вы решили выбрать фильм для совместного просмотра. Ваш племянник - фанат "Jurassic Park". Вы предположили, что ему понравится фильм того же кинорежиссера. Однако стоит учесть ограничение по возрасту (класс фильма). Выберите фильм из базы IMDb-5000 с рейтингом более 7.0 для совместного просмотра с племянником

Кинорежиссер фильма "Jurassic Park" - Steven Spielberg. Отфильтруйте датасет, оставив только его фильмы, и сохраните результаты в переменную filtered_dataset

In [50]:
filter = dataset['director'] == 'Steven Spielberg'
filtered_dataset = dataset[filter]

filtered_dataset.head()

poster  \
4    https://m.media-amazon.com/images/S/sash/4Fyxw...   
24   https://m.media-amazon.com/images/S/sash/4Fyxw...   
75   https://m.media-amazon.com/images/S/sash/4Fyxw...   
160  https://m.media-amazon.com/images/S/sash/4Fyxw...   
168  https://m.media-amazon.com/images/S/sash/4Fyxw...   

                                  title certificate  runtime  \
4                      Schindler's List          15  195 min   
24                  Saving Private Ryan          15  169 min   
75              Raiders of the Lost Ark           A  115 min   
160                       Jurassic Park          PG  127 min   
168  Indiana Jones and the Last Crusade          PG  127 min   

                         genre  rating  \
4    Biography, Drama, History     9.0   
24                  Drama, War     8.6   
75           Action, Adventure     8.4   
160  Action, Adventure, Sci-Fi     8.2   
168          Action, Adventure     8.2   

                                                 about          director  \
4    In German-occupied Poland during World War II,...  Steven Spielberg   
24   Following the Normandy Landings, a group of U....  Steven Spielberg   
75   Archaeology professor Indiana Jones ventures t...  Steven Spielberg   
160  A pragmatic paleontologist touring an almost c...  Steven Spielberg   
168  In 1938, after his father Professor Henry Jone...  Steven Spielberg   

                                                 stars      votes gross_earn  \
4    ('Liam Neeson',), ('Ralph Fiennes',), ('Ben Ki...  13,33,407    $96.90M   
24   ('Tom Hanks',), ('Matt Damon',), ('Tom Sizemor...  13,66,343   $216.54M   
75   ('Harrison Ford',), ('Karen Allen',), ('Paul F...   9,53,762   $248.16M   
160  ('Sam Neill',), ('Laura Dern',), ('Jeff Goldbl...   9,73,121   $402.45M   
168  ('Harrison Ford',), ('Sean Connery',), ('Aliso...   7,45,875   $197.17M   

     runtime_clear  gross_earn_clear  
4              195             96.90  
24             169            216.54  
75             115            248.16  
160            127            402.45  
168            127            197.17

Оцените размеры датасета с помощью атрибута shape

In [10]:
filtered_dataset.shape

(27, 13)

Отфильтруйте датасет, оставив фильмы с рейтингом выше 7.0 баллов, и сохраните результаты  в переменную filtered_dataset_2

In [11]:
filter_2 = dataset['rating'] > 7.0
filtered_dataset_2 = filtered_dataset[filter_2]

filtered_dataset_2.head()

<ipython-input-11-d1bc336651c9>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  filtered_dataset_2 = filtered_dataset[filter_2]


poster  \
4    https://m.media-amazon.com/images/S/sash/4Fyxw...   
24   https://m.media-amazon.com/images/S/sash/4Fyxw...   
75   https://m.media-amazon.com/images/S/sash/4Fyxw...   
160  https://m.media-amazon.com/images/S/sash/4Fyxw...   
168  https://m.media-amazon.com/images/S/sash/4Fyxw...   

                                  title certificate  runtime  \
4                      Schindler's List          15  195 min   
24                  Saving Private Ryan          15  169 min   
75              Raiders of the Lost Ark           A  115 min   
160                       Jurassic Park          PG  127 min   
168  Indiana Jones and the Last Crusade          PG  127 min   

                         genre  rating  \
4    Biography, Drama, History     9.0   
24                  Drama, War     8.6   
75           Action, Adventure     8.4   
160  Action, Adventure, Sci-Fi     8.2   
168          Action, Adventure     8.2   

                                                 about          director  \
4    In German-occupied Poland during World War II,...  Steven Spielberg   
24   Following the Normandy Landings, a group of U....  Steven Spielberg   
75   Archaeology professor Indiana Jones ventures t...  Steven Spielberg   
160  A pragmatic paleontologist touring an almost c...  Steven Spielberg   
168  In 1938, after his father Professor Henry Jone...  Steven Spielberg   

                                                 stars      votes gross_earn  \
4    ('Liam Neeson',), ('Ralph Fiennes',), ('Ben Ki...  13,33,407    $96.90M   
24   ('Tom Hanks',), ('Matt Damon',), ('Tom Sizemor...  13,66,343   $216.54M   
75   ('Harrison Ford',), ('Karen Allen',), ('Paul F...   9,53,762   $248.16M   
160  ('Sam Neill',), ('Laura Dern',), ('Jeff Goldbl...   9,73,121   $402.45M   
168  ('Harrison Ford',), ('Sean Connery',), ('Aliso...   7,45,875   $197.17M   

     runtime_clear  gross_earn_clear  
4              195             96.90  
24             169            216.54  
75             115            248.16  
160            127            402.45  
168            127            197.17

Оцените размеры датасета с помощью атрибута shape

In [12]:
filtered_dataset_2.shape

(21, 13)

Выведите список уникальных значений классов фильмов с помощью метода unique()

In [13]:
filtered_dataset_2['certificate'].unique()

array(['15', 'A', 'PG', '12A', 'U', '12'], dtype=object)

Из данных классов нам подходят:
*   A (с детского возраста под присмотром родителей по старой классификации)
*   PG (с детского возраста под присмотром родителей)
*   U (для людей всех возрастов)
*   UA (для людей всех возрастов, под присмотром родителей по старой классификации)

Отфильтруйте датасет, оставив фильмы разрешенные к просмотру ребенку 10 лет, с помощью метода isin() и сохраните результаты в переменную filtered_dataset_3

In [14]:
certificate = ['A', 'PG', 'U', 'UA']

filter_3 = filtered_dataset_2['certificate'].isin(certificate)

filtered_dataset_3 = filtered_dataset_2[filter_3]

filtered_dataset_3.head()

poster  \
75   https://m.media-amazon.com/images/S/sash/4Fyxw...   
160  https://m.media-amazon.com/images/S/sash/4Fyxw...   
168  https://m.media-amazon.com/images/S/sash/4Fyxw...   
253  https://m.media-amazon.com/images/S/sash/4Fyxw...   
477  https://m.media-amazon.com/images/S/sash/4Fyxw...   

                                  title certificate  runtime  \
75              Raiders of the Lost Ark           A  115 min   
160                       Jurassic Park          PG  127 min   
168  Indiana Jones and the Last Crusade          PG  127 min   
253                                Jaws           A  124 min   
477          E.T. the Extra-Terrestrial           U  115 min   

                         genre  rating  \
75           Action, Adventure     8.4   
160  Action, Adventure, Sci-Fi     8.2   
168          Action, Adventure     8.2   
253        Adventure, Thriller     8.1   
477  Adventure, Family, Sci-Fi     7.9   

                                                 about          director  \
75   Archaeology professor Indiana Jones ventures t...  Steven Spielberg   
160  A pragmatic paleontologist touring an almost c...  Steven Spielberg   
168  In 1938, after his father Professor Henry Jone...  Steven Spielberg   
253  When a killer shark unleashes chaos on a beach...  Steven Spielberg   
477  A troubled child summons the courage to help a...  Steven Spielberg   

                                                 stars     votes gross_earn  \
75   ('Harrison Ford',), ('Karen Allen',), ('Paul F...  9,53,762   $248.16M   
160  ('Sam Neill',), ('Laura Dern',), ('Jeff Goldbl...  9,73,121   $402.45M   
168  ('Harrison Ford',), ('Sean Connery',), ('Aliso...  7,45,875   $197.17M   
253  ('Roy Scheider',), ('Robert Shaw',), ('Richard...  5,94,722   $260.00M   
477  ('Henry Thomas',), ('Drew Barrymore',), ('Pete...  4,03,782   $435.11M   

     runtime_clear  gross_earn_clear  
75             115            248.16  
160            127            402.45  
168            127            197.17  
253            124            260.00  
477            115            435.11

Оцените размеры датасета с помощью атрибута shape

In [15]:
filtered_dataset_3.shape

(8, 13)

Исключите фильмы, которые племянник уже пересмотрел:
*   Jurassic Park
*   Indiana Jones and the Last Crusade
*   Jaws

И выберите самый короткий фильм из оставшихся

Для этого сохраните список фильмов в переменную stop_films и отфильтруйте датасет по нему с помощью метода isin(), а также по минимальной продолжительности фильмов, определенной с помощью метода min(), сохранив результаты в переменную filtered_dataset_4

In [16]:
stop_films = ['Jurassic Park', 'Indiana Jones and the Last Crusade', 'Jaws']

filter_4 = ~(filtered_dataset_3['title'].isin(stop_films)) & (filtered_dataset_3['runtime_clear'].min()==filtered_dataset_3['runtime_clear'])

filtered_dataset_4 = filtered_dataset_3[filter_4]

filtered_dataset_4.head()

poster  \
1324  https://m.media-amazon.com/images/S/sash/4Fyxw...   

                                                  title certificate  runtime  \
1324  The Adventures of Tintin: The Secret of the Un...          PG  107 min   

                             genre  rating  \
1324  Animation, Action, Adventure     7.3   

                                                  about          director  \
1324  Intrepid reporter Tintin and Captain Haddock s...  Steven Spielberg   

                                                  stars     votes gross_earn  \
1324  ('Jamie Bell',), ('Andy Serkis',), ('Daniel Cr...  2,30,302    $77.59M   

      runtime_clear  gross_earn_clear  
1324            107             77.59

Выведите наименование фильма с помощью индексации и оцените Ваш выбор

In [17]:
filtered_dataset_4['title'][1324]

'The Adventures of Tintin: The Secret of the Unicorn'

Думаю, племянник будет доволен!

### **5.2. Фильм на вечер для себя*

По аналогии отфильтруйте датасет таким образом, чтобы выбрать фильм на вечер для себя (по собственным критериям).
Описание: Я люблю смотреть Квентина Тарантино. Смотрел самые популярные его фильмы, но руки так и не дошли до "Reservoir dogs".
Думаю, что время настало... =)

In [22]:
# Я знаю конкретного режиссера и название фильма, поэтому создам сложный фильтр.
filter = (dataset['director'] == 'Quentin Tarantino') & (dataset['title'] == 'Reservoir Dogs')
filtered_dataset = dataset[filter]

filtered_dataset.head()

poster           title  \
99  https://m.media-amazon.com/images/S/sash/4Fyxw...  Reservoir Dogs   

   certificate runtime                   genre  rating  \
99          18  99 min  Crime, Drama, Thriller     8.3   

                                                about           director  \
99  When a simple jewelry heist goes horribly wron...  Quentin Tarantino   

                                                stars      votes gross_earn  \
99  ('Harvey Keitel',), ('Tim Roth',), ('Michael M...  10,02,382     $2.83M   

    runtime_clear  gross_earn_clear  
99             99              2.83

In [41]:
# Прочитаем, о чем собственно фильм.
filtered_dataset['about'][99]

'When a simple jewelry heist goes horribly wrong, the surviving criminals begin to suspect that one of them is a police informant.'

In [42]:
# Кто в главных ролях
filtered_dataset['stars'][99]

"('Harvey Keitel',), ('Tim Roth',), ('Michael Madsen',), ('Chris Penn',)"

In [44]:
# А продолжительность фильма?
filtered_dataset['runtime'][99]
# Нормально

'99 min'

## 6. Срезы

### *6.1. Выбираем еще 2 детских фильма, близких по рейтингу к выбранному*

**Описание:** племяннику очень понравился выбранный Вами фильм. Он попросил выбрать еще 2 анимационных фильма, близких по рейтингу к данному (кинорежиссер значения не имеет). Подберите 2 подходящих фильма для племянника

Необходимо вспомнить информацию о фильме, который Вы выбрали в прошлый раз. Его индекс в базе - 1324. Из исходного датасета dataset выведите информацию о фильме, используя метод loc[]

In [45]:
dataset.loc[1324]

poster              https://m.media-amazon.com/images/S/sash/4Fyxw...
title               The Adventures of Tintin: The Secret of the Un...
certificate                                                        PG
runtime                                                       107 min
genre                                    Animation, Action, Adventure
rating                                                            7.3
about               Intrepid reporter Tintin and Captain Haddock s...
director                                             Steven Spielberg
stars               ('Jamie Bell',), ('Andy Serkis',), ('Daniel Cr...
votes                                                        2,30,302
gross_earn                                                    $77.59M
runtime_clear                                                     107
gross_earn_clear                                                77.59
Name: 1324, dtype: object

Выведите описание фильма (about), используя метод loc[]

In [46]:
dataset.loc[1324].about

"Intrepid reporter Tintin and Captain Haddock set off on a treasure hunt for a sunken ship commanded by Haddock's ancestor."

В части 1 тренировочного задания датасет был отсортирован по убыванию рейтинга. Значит фильмы, близкие по рейтину к выбранному фильму, находятся Сократите диапазон поиска, выбрав срез фильмов от 1320 строки до 1330 строки, используя метод loc[] и оцените результаты

In [47]:
dataset.loc[1320:1330]

poster  \
1320  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1321  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1322  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1323  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1324  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1325  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1326  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1327  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1328  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1329  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1330  https://m.media-amazon.com/images/S/sash/4Fyxw...   

                                                  title certificate  runtime  \
1320                      Star Trek IV: The Voyage Home          PG  119 min   
1321                       Murder on the Orient Express           A  128 min   
1322                                                Big           U  104 min   
1323                                         Cinderella           U   74 min   
1324  The Adventures of Tintin: The Secret of the Un...          PG  107 min   
1325                                   Barney's Version          15  134 min   
1326                                              Frida          15  123 min   
1327                                  Starship Troopers          15  129 min   
1328                                    Despicable Me 2           U   98 min   
1329                                      Thirteen Days          12  145 min   
1330                                    Murder by Death           A   95 min   

                             genre  rating  \
1320     Action, Adventure, Comedy     7.3   
1321         Crime, Drama, Mystery     7.3   
1322        Comedy, Drama, Fantasy     7.3   
1323    Animation, Family, Fantasy     7.3   
1324  Animation, Action, Adventure     7.3   
1325                 Comedy, Drama     7.3   
1326     Biography, Drama, Romance     7.3   
1327     Action, Adventure, Sci-Fi     7.3   
1328  Animation, Adventure, Comedy     7.3   
1329      Drama, History, Thriller     7.3   
1330        Comedy, Crime, Mystery     7.3   

                                                  about          director  \
1320  To save Earth from an alien probe, Admiral Jam...     Leonard Nimoy   
1321  In December 1935, when his transcontinental lu...      Sidney Lumet   
1322  After wishing to be made big, a teenage boy wa...    Penny Marshall   
1323  When Cinderella's cruel stepmother prevents he...    Clyde Geronimi   
1324  Intrepid reporter Tintin and Captain Haddock s...  Steven Spielberg   
1325  The picaresque and touching story of the polit...  Richard J. Lewis   
1326                              A biography of artist      Julie Taymor   
1327  Humans in a fascist, militaristic future wage ...    Paul Verhoeven   
1328  When Gru, the world's most super-bad turned su...     Pierre Coffin   
1329  In October 1962, the Kennedy administration st...   Roger Donaldson   
1330  Five famous literary detective characters and ...      Robert Moore   

                                                  stars     votes gross_earn  \
1320  ('William Shatner',), ('Leonard Nimoy',), ('De...    85,374   $109.71M   
1321  ('Albert Finney',), ('Lauren Bacall',), ('Ingr...    62,253     $0.07M   
1322  ('Tom Hanks',), ('Elizabeth Perkins',), ('Robe...  2,18,714   $114.97M   
1323  ('Wilfred Jackson',), ('Hamilton Luske',), ('I...  1,59,181    $85.00M   
1324  ('Jamie Bell',), ('Andy Serkis',), ('Daniel Cr...  2,30,302    $77.59M   
1325  ('Paul Giamatti',), ('Rosamund Pike',), ('Jake...    25,191     $7.50M   
1326  ('Salma Hayek',), ('Alfred Molina',), ('Geoffr...    89,676    $25.89M   
1327  ('Casper Van Dien',), ('Denise Richards',), ('...  2,93,136    $54.81M   
1328  ('Chris Renaud',), ('Steve Carell',), ('Kriste...  3,97,340   $368.06M   
1329  ('Kevin Costner',), ('Bruce Greenwood',), ('Sh...    58,860    $34.59M   
1330  ('Peter Falk',)

Из полученных в результате среза фильмов подходят только фильмы жанра Animation (ограничения по возрасту они также не противоречат). Это фильмы с индексами 1323 и 1328

Сохраните в переменную index_list список индексов трех фильмов, которые Вы выбрали для племянника (включая самый первый с индексом 1324) и выведите отфильтрованный с помощью метода loc[] датасет

In [48]:
index_list = [1324,1323,1328]
dataset.loc[index_list]

poster  \
1324  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1323  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1328  https://m.media-amazon.com/images/S/sash/4Fyxw...   

                                                  title certificate  runtime  \
1324  The Adventures of Tintin: The Secret of the Un...          PG  107 min   
1323                                         Cinderella           U   74 min   
1328                                    Despicable Me 2           U   98 min   

                             genre  rating  \
1324  Animation, Action, Adventure     7.3   
1323    Animation, Family, Fantasy     7.3   
1328  Animation, Adventure, Comedy     7.3   

                                                  about          director  \
1324  Intrepid reporter Tintin and Captain Haddock s...  Steven Spielberg   
1323  When Cinderella's cruel stepmother prevents he...    Clyde Geronimi   
1328  When Gru, the world's most super-bad turned su...     Pierre Coffin   

                                                  stars     votes gross_earn  \
1324  ('Jamie Bell',), ('Andy Serkis',), ('Daniel Cr...  2,30,302    $77.59M   
1323  ('Wilfred Jackson',), ('Hamilton Luske',), ('I...  1,59,181    $85.00M   
1328  ('Chris Renaud',), ('Steve Carell',), ('Kriste...  3,97,340   $368.06M   

      runtime_clear  gross_earn_clear  
1324            107             77.59  
1323             74             85.00  
1328             98            368.06

Ваш племянник в восторге! Спасибо за помощь!



### *6.2. Выбираем показатели описательной статистики по фильмам кинорежиссера Steven Spielberg*

**Описание:** в переменной filtered_dataset ранее был сохранен датасет с фильмами кинорежиссера Steven Spielberg. Выберите различные показатели описательной статистики

Выведите показатели описательной статистики с помощью метода describe() и сохраните результат в переменную described_data

Надо поднятся до первого задания и в filtered_dataset опять сохранить Спилберга. А сейчас в этой переменной "Бешеные псы" Тарантино.

In [51]:
described_data = filtered_dataset.describe()
described_data

rating  runtime_clear  gross_earn_clear
count  27.000000      27.000000         27.000000
mean    7.466667     137.333333        156.351481
std     0.762082      20.038425        109.644047
min     5.800000     107.000000         22.240000
25%     7.200000     122.000000         77.730000
50%     7.500000     138.000000        132.070000
75%     8.000000     148.000000        222.815000
max     9.000000     195.000000        435.110000

Выведите строку с минимальными значениями с помощью метода loc[]

In [53]:
described_data.loc['min']

rating                5.80
runtime_clear       107.00
gross_earn_clear     22.24
Name: min, dtype: float64

Выведите срез строк от 50% процентиля до максимального значения с помощью метода loc[]

In [54]:
described_data.loc['50%':'max']

rating  runtime_clear  gross_earn_clear
50%     7.5          138.0           132.070
75%     8.0          148.0           222.815
max     9.0          195.0           435.110

Выведите для сравнения показатели среднего значения (mean) и медианы (50% процентиль) с помощью метода loc[], предварительно сохранив их в переменную stat_names список наименований индексов

In [55]:
stat_names = ['mean', '50%']
described_data.loc[stat_names]

rating  runtime_clear  gross_earn_clear
mean  7.466667     137.333333        156.351481
50%   7.500000     138.000000        132.070000

Выведите срез от минимального (min) до максимального (max) значения, используя метод iloc

In [60]:
described_data.iloc[3 : 8]

rating  runtime_clear  gross_earn_clear
min     5.8          107.0            22.240
25%     7.2          122.0            77.730
50%     7.5          138.0           132.070
75%     8.0          148.0           222.815
max     9.0          195.0           435.110

### **6.3. Выбираем еще 5 фильмов на вечер, близких по рейтингу к выбранному ранее*

По аналогии отберите 5 фильмов на вечер, близких по рейтингу к выбранному ранее

In [61]:
# Выводим dataset, где только фильмы Спилберга.
filtered_dataset.head()

poster  \
4    https://m.media-amazon.com/images/S/sash/4Fyxw...   
24   https://m.media-amazon.com/images/S/sash/4Fyxw...   
75   https://m.media-amazon.com/images/S/sash/4Fyxw...   
160  https://m.media-amazon.com/images/S/sash/4Fyxw...   
168  https://m.media-amazon.com/images/S/sash/4Fyxw...   

                                  title certificate  runtime  \
4                      Schindler's List          15  195 min   
24                  Saving Private Ryan          15  169 min   
75              Raiders of the Lost Ark           A  115 min   
160                       Jurassic Park          PG  127 min   
168  Indiana Jones and the Last Crusade          PG  127 min   

                         genre  rating  \
4    Biography, Drama, History     9.0   
24                  Drama, War     8.6   
75           Action, Adventure     8.4   
160  Action, Adventure, Sci-Fi     8.2   
168          Action, Adventure     8.2   

                                                 about          director  \
4    In German-occupied Poland during World War II,...  Steven Spielberg   
24   Following the Normandy Landings, a group of U....  Steven Spielberg   
75   Archaeology professor Indiana Jones ventures t...  Steven Spielberg   
160  A pragmatic paleontologist touring an almost c...  Steven Spielberg   
168  In 1938, after his father Professor Henry Jone...  Steven Spielberg   

                                                 stars      votes gross_earn  \
4    ('Liam Neeson',), ('Ralph Fiennes',), ('Ben Ki...  13,33,407    $96.90M   
24   ('Tom Hanks',), ('Matt Damon',), ('Tom Sizemor...  13,66,343   $216.54M   
75   ('Harrison Ford',), ('Karen Allen',), ('Paul F...   9,53,762   $248.16M   
160  ('Sam Neill',), ('Laura Dern',), ('Jeff Goldbl...   9,73,121   $402.45M   
168  ('Harrison Ford',), ('Sean Connery',), ('Aliso...   7,45,875   $197.17M   

     runtime_clear  gross_earn_clear  
4              195             96.90  
24             169            216.54  
75             115            248.16  
160            127            402.45  
168            127            197.17

In [69]:
# Смотрим сколько там фильмов.
filtered_dataset.shape

(27, 13)

In [70]:
# Проверяем описательную статистику.
described_data = filtered_dataset.describe()
described_data

rating  runtime_clear  gross_earn_clear
count  27.000000      27.000000         27.000000
mean    7.466667     137.333333        156.351481
std     0.762082      20.038425        109.644047
min     5.800000     107.000000         22.240000
25%     7.200000     122.000000         77.730000
50%     7.500000     138.000000        132.070000
75%     8.000000     148.000000        222.815000
max     9.000000     195.000000        435.110000

In [71]:
# Выбираем срез рейтингов.
described_data.loc['25%':'75%']

rating  runtime_clear  gross_earn_clear
25%     7.2          122.0            77.730
50%     7.5          138.0           132.070
75%     8.0          148.0           222.815

In [113]:
# Выбираем фильмы по срезу рейтингов, исключая "Приключения Тинтина...".
stop_film = ['The Adventures of Tintin: The Secret of the Unicorn']
ratings = [7.2, 7.3, 7.5, 7.8, 7.9, 8.0]
filter_6 = ~(filtered_dataset['title'].isin(stop_film)) & (filtered_dataset['rating'].isin(ratings))
filtered_dataset_6 = filtered_dataset[filter_6]
filtered_dataset_6.head()

poster  \
477   https://m.media-amazon.com/images/S/sash/4Fyxw...   
1016  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1075  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1394  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1482  https://m.media-amazon.com/images/S/sash/4Fyxw...   

                                     title certificate  runtime  \
477             E.T. the Extra-Terrestrial           U  115 min   
1016  Indiana Jones and the Temple of Doom         12A  118 min   
1075                                Munich          15  164 min   
1394                               Amistad          15  155 min   
1482                               Lincoln         12A  150 min   

                          genre  rating  \
477   Adventure, Family, Sci-Fi     7.9   
1016          Action, Adventure     7.5   
1075     Action, Drama, History     7.5   
1394  Biography, Drama, History     7.3   
1482  Biography, Drama, History     7.3   

                                                  about          director  \
477   A troubled child summons the courage to help a...  Steven Spielberg   
1016  A skirmish in Shanghai puts archaeologist Indi...  Steven Spielberg   
1075  After the Black September capture and massacre...  Steven Spielberg   
1394  In 1839, the revolt of Mende captives aboard a...  Steven Spielberg   
1482  As the American Civil War continues to rage, A...  Steven Spielberg   

                                                  stars     votes gross_earn  \
477   ('Henry Thomas',), ('Drew Barrymore',), ('Pete...  4,03,782   $435.11M   
1016  ('Harrison Ford',), ('Kate Capshaw',), ('Ke Hu...  4,83,027   $179.87M   
1075  ('Eric Bana',), ('Daniel Craig',), ('Marie-Jos...  2,26,092    $47.40M   
1394  ('Djimon Hounsou',), ('Matthew McConaughey',),...    76,897    $44.18M   
1482  ('Daniel Day-Lewis',), ('Sally Field',), ('Dav...  2,59,718   $182.21M   

      runtime_clear  gross_earn_clear  
477             115            435.11  
1016            118            179.87  
1075            164             47.40  
1394            155             44.18  
1482            150            182.21

In [114]:
# Выбираем 5 фильмов по срезу
filtered_dataset_6.loc[477:1482]

poster  \
477   https://m.media-amazon.com/images/S/sash/4Fyxw...   
1016  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1075  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1394  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1482  https://m.media-amazon.com/images/S/sash/4Fyxw...   

                                     title certificate  runtime  \
477             E.T. the Extra-Terrestrial           U  115 min   
1016  Indiana Jones and the Temple of Doom         12A  118 min   
1075                                Munich          15  164 min   
1394                               Amistad          15  155 min   
1482                               Lincoln         12A  150 min   

                          genre  rating  \
477   Adventure, Family, Sci-Fi     7.9   
1016          Action, Adventure     7.5   
1075     Action, Drama, History     7.5   
1394  Biography, Drama, History     7.3   
1482  Biography, Drama, History     7.3   

                                                  about          director  \
477   A troubled child summons the courage to help a...  Steven Spielberg   
1016  A skirmish in Shanghai puts archaeologist Indi...  Steven Spielberg   
1075  After the Black September capture and massacre...  Steven Spielberg   
1394  In 1839, the revolt of Mende captives aboard a...  Steven Spielberg   
1482  As the American Civil War continues to rage, A...  Steven Spielberg   

                                                  stars     votes gross_earn  \
477   ('Henry Thomas',), ('Drew Barrymore',), ('Pete...  4,03,782   $435.11M   
1016  ('Harrison Ford',), ('Kate Capshaw',), ('Ke Hu...  4,83,027   $179.87M   
1075  ('Eric Bana',), ('Daniel Craig',), ('Marie-Jos...  2,26,092    $47.40M   
1394  ('Djimon Hounsou',), ('Matthew McConaughey',),...    76,897    $44.18M   
1482  ('Daniel Day-Lewis',), ('Sally Field',), ('Dav...  2,59,718   $182.21M   

      runtime_clear  gross_earn_clear  
477             115            435.11  
1016            118            179.87  
1075            164             47.40  
1394            155             44.18  
1482            150            182.21

### **6.4. Выбираем показатели описательной статистики по фильмам кинорежиссера Woody Allen*

По аналогии отфильтруйте датасет по фильмам кинорежиссера Woody Allen и выберите показатели описательной статистики

In [115]:
# Фильтруем данные по режиссеру.
filter = dataset['director'] == 'Woody Allen'
filtered_dataset = dataset[filter]

filtered_dataset.head()

poster  \
329  https://m.media-amazon.com/images/S/sash/4Fyxw...   
464  https://m.media-amazon.com/images/S/sash/4Fyxw...   
500  https://m.media-amazon.com/images/S/sash/4Fyxw...   
636  https://m.media-amazon.com/images/S/sash/4Fyxw...   
717  https://m.media-amazon.com/images/S/sash/4Fyxw...   

                       title certificate  runtime                   genre  \
329               Annie Hall          AA   93 min         Comedy, Romance   
464   Hannah and Her Sisters          15  107 min           Comedy, Drama   
500                Manhattan          AA   96 min  Comedy, Drama, Romance   
636  Crimes and Misdemeanors          15  104 min           Comedy, Drama   
717           Love and Death           A   85 min             Comedy, War   

     rating                                              about     director  \
329     8.0  Alvy Singer, a divorced Jewish comedian, refle...  Woody Allen   
464     7.9  Between two Thanksgivings two years apart, Han...  Woody Allen   
500     7.9  The life of a divorced television writer datin...  Woody Allen   
636     7.8  An ophthalmologist's mistress threatens to rev...  Woody Allen   
717     7.7  In czarist Russia, a neurotic soldier and his ...  Woody Allen   

                                                 stars     votes gross_earn  \
329  ('Woody Allen',), ('Diane Keaton',), ('Tony Ro...  2,64,502    $39.20M   
464  ('Mia Farrow',), ('Dianne Wiest',), ('Michael ...    71,500    $40.08M   
500  ('Woody Allen',), ('Diane Keaton',), ('Mariel ...  1,39,889    $45.70M   
636  ('Martin Landau',), ('Woody Allen',), ('Bill B...    57,988    $18.25M   
717  ('Woody Allen',), ('Diane Keaton',), ('Georges...    38,572        NaN   

     runtime_clear  gross_earn_clear  
329             93             39.20  
464            107             40.08  
500             96             45.70  
636            104             18.25  
717             85               NaN

In [116]:
# Смотрим кол-во фильмов
filtered_dataset.shape

(38, 13)

In [117]:
# Выводим показатели описательной статистики (медиану,std(показатель рассеивания значений случайной величины относительно её математического ожидания), мин, макс и процентили) с помощью метода describe()
described_data = filtered_dataset.describe()
described_data

rating  runtime_clear  gross_earn_clear
count  38.000000      38.000000         36.000000
mean    7.092105      97.052632         14.241667
std     0.523699       9.921169         13.294116
min     6.300000      79.000000          0.720000
25%     6.600000      90.000000          4.982500
50%     7.150000      96.000000         10.580000
75%     7.475000     103.750000         16.785000
max     8.000000     124.000000         56.820000

In [118]:
# Смотри мин значения в списке фильмов
described_data.loc['min']

rating               6.30
runtime_clear       79.00
gross_earn_clear     0.72
Name: min, dtype: float64

In [119]:
# Смотрим значения от 50-го процентиля до макс
described_data.loc['50%':'max']

rating  runtime_clear  gross_earn_clear
50%   7.150          96.00            10.580
75%   7.475         103.75            16.785
max   8.000         124.00            56.820

In [120]:
#Сравниваем медиану и 50-ый процентиль показателей
stat_names = ['mean', '50%']
described_data.loc[stat_names]

rating  runtime_clear  gross_earn_clear
mean  7.092105      97.052632         14.241667
50%   7.150000      96.000000         10.580000

In [121]:
# Выводим диапазон от мин до макс
described_data.iloc[3 : 8]

rating  runtime_clear  gross_earn_clear
min   6.300          79.00            0.7200
25%   6.600          90.00            4.9825
50%   7.150          96.00           10.5800
75%   7.475         103.75           16.7850
max   8.000         124.00           56.8200

## 7. Продвинутая фильтрация

### *7.1. Отбираем все фильмы жанра Adventure*

**Описание:** отберите все фильмы, которые относятся к приключенческому жанру (Adventure)

Напишите функцию is_genre_correct(), которая с помощью оператора in будет искать вхождение подстроки с наименованием жанра по признаку genre

In [122]:
def is_genre_correct(genre):
  return 'Adventure' in genre

Создайте фильтр filter_5, применив функцию is_genre_correct к столбцу genre

In [123]:
filter_5 = dataset['genre'].apply(is_genre_correct)
filter_5

0       False
1       False
2       False
3       False
4       False
        ...  
4965     True
4966    False
4967    False
4968    False
4969    False
Name: genre, Length: 4970, dtype: bool

Отфильтруйте датасет с помощью фильтра filter_5 и сохраните результаты в переменную filtered_dataset_5

In [124]:
filtered_dataset_5 = dataset[filter_5]
filtered_dataset_5.head()

poster  \
6   https://m.media-amazon.com/images/S/sash/4Fyxw...   
9   https://m.media-amazon.com/images/S/sash/4Fyxw...   
11  https://m.media-amazon.com/images/S/sash/4Fyxw...   
13  https://m.media-amazon.com/images/S/sash/4Fyxw...   
14  https://m.media-amazon.com/images/S/sash/4Fyxw...   

                                                title certificate  runtime  \
6       The Lord of the Rings: The Return of the King         12A  201 min   
9   The Lord of the Rings: The Fellowship of the Ring          PG  178 min   
11              The Lord of the Rings: The Two Towers         12A  179 min   
13                                          Inception         12A  148 min   
14                     The Good, the Bad and the Ugly           X  148 min   

                        genre  rating  \
6    Action, Adventure, Drama     9.0   
9    Action, Adventure, Drama     8.8   
11   Action, Adventure, Drama     8.8   
13  Action, Adventure, Sci-Fi     8.8   
14         Adventure, Western     8.8   

                                                about           director  \
6   Gandalf and Aragorn lead the World of Men agai...      Peter Jackson   
9   A meek Hobbit from the Shire and eight compani...      Peter Jackson   
11  While Frodo and Sam edge closer to Mordor with...      Peter Jackson   
13  A thief who steals corporate secrets through t...  Christopher Nolan   
14  A bounty hunting scam joins two men in an unea...       Sergio Leone   

                                                stars      votes gross_earn  \
6   ('Elijah Wood',), ('Viggo Mortensen',), ('Ian ...  18,01,662   $377.85M   
9   ('Elijah Wood',), ('Ian McKellen',), ('Orlando...  18,23,037   $315.54M   
11  ('Elijah Wood',), ('Ian McKellen',), ('Viggo M...  16,26,871   $342.55M   
13  ('Leonardo DiCaprio',), ('Joseph Gordon-Levitt...  23,04,062   $292.58M   
14  ('Clint Eastwood',), ('Eli Wallach',), ('Lee V...   7,51,207     $6.10M   

    runtime_clear  gross_earn_clear  
6             201            377.85  
9             178            315.54  
11            179            342.55  
13            148            292.58  
14            148              6.10

Оцените размеры датасета с помощью атрибута shape

In [125]:
filtered_dataset_5.shape

(1011, 13)

Отличная работа! Вы собрали все приключенческие фильмы!

### *7.2. Отфильтруем все числовые колонки*

**Описание:** отфильтруйте числовые колонки исходного датасета dataset

Выведите список признаков с указанием их типов с помощью атрибута dtypes и сохраните результаты в переменную dtypes

In [126]:
dtypes = dataset.dtypes
dtypes

poster               object
title                object
certificate          object
runtime              object
genre                object
rating              float64
about                object
director             object
stars                object
votes                object
gross_earn           object
runtime_clear         int64
gross_earn_clear    float64
dtype: object

Отфильтруйте все числовые колонки и сохраните результаты в переменную num_dtypes

In [127]:
num_dtypes = dtypes[dtypes!=object]
num_dtypes

rating              float64
runtime_clear         int64
gross_earn_clear    float64
dtype: object

Сохраните в переменную new_columns список наименований отфильтрованных колонок, используя атрибут index

In [128]:
new_columns = num_dtypes.index
new_columns

Index(['rating', 'runtime_clear', 'gross_earn_clear'], dtype='object')

Отфильтруйте исходный датасет, оставив только числовые колонки, и сохраните результат в переменную filtered_dataset_6

In [132]:
filtered_dataset_6 = dataset[new_columns]
filtered_dataset_6.head()

rating  runtime_clear  gross_earn_clear
0     9.3            142             28.34
1     9.2             87               NaN
2     9.2            175            134.97
3     9.0            202             57.30
4     9.0            195             96.90

Все получилось!

### **7.3. Отбираем все фильмы, где снимался Leonardo DiCaprio*

По аналогии отберите фильмы, где снимался Leonardo DiCaprio

Опять же, я сохраняю в filter_5 новые данные. Если необходимо, вверху надо пересохранить

In [133]:
# Пишем функцию на отсев Дикаприо
def is_stars_correct(stars):
  return 'Leonardo DiCaprio' in stars

In [134]:
# Пименяем фильтр-функцию к датасету
filter_5 = dataset['stars'].apply(is_stars_correct)
filter_5

0       False
1       False
2       False
3       False
4       False
        ...  
4965    False
4966    False
4967    False
4968    False
4969    False
Name: stars, Length: 4970, dtype: bool

In [135]:
# Смотрим отфильтрованный датасет
filtered_dataset_5 = dataset[filter_5]
filtered_dataset_5.head()

poster  \
13   https://m.media-amazon.com/images/S/sash/4Fyxw...   
52   https://m.media-amazon.com/images/S/sash/4Fyxw...   
72   https://m.media-amazon.com/images/S/sash/4Fyxw...   
165  https://m.media-amazon.com/images/S/sash/4Fyxw...   
167  https://m.media-amazon.com/images/S/sash/4Fyxw...   

                       title certificate  runtime                      genre  \
13                 Inception         12A  148 min  Action, Adventure, Sci-Fi   
52              The Departed          18  151 min     Crime, Drama, Thriller   
72          Django Unchained          18  165 min             Drama, Western   
165  The Wolf of Wall Street          18  180 min   Biography, Comedy, Crime   
167           Shutter Island          15  138 min          Mystery, Thriller   

     rating                                              about  \
13      8.8  A thief who steals corporate secrets through t...   
52      8.5  An undercover cop and a mole in the police att...   
72      8.4  With the help of a German bounty-hunter, a fre...   
165     8.2                         Based on the true story of   
167     8.2  In 1954, a U.S. Marshal investigates the disap...   

              director                                              stars  \
13   Christopher Nolan  ('Leonardo DiCaprio',), ('Joseph Gordon-Levitt...   
52     Martin Scorsese  ('Leonardo DiCaprio',), ('Matt Damon',), ('Jac...   
72   Quentin Tarantino  ('Jamie Foxx',), ('Christoph Waltz',), ('Leona...   
165    Martin Scorsese  ('Leonardo DiCaprio',), ('Jonah Hill',), ('Mar...   
167    Martin Scorsese  ('Leonardo DiCaprio',), ('Emily Mortimer',), (...   

         votes gross_earn  runtime_clear  gross_earn_clear  
13   23,04,062   $292.58M            148            292.58  
52   13,03,531   $132.38M            151            132.38  
72   15,19,581   $162.81M            165            162.81  
165  13,69,335   $116.90M            180            116.90  
167  12,80,796   $128.01M            138            128.01

In [136]:
# Леонардо Дикаприо снимался в 24 фильмах
filtered_dataset_5.shape

(24, 13)

### **7.4. Отфильтруем все нечисловые колонки*

По аналогии отфильтруйте все нечисловые колонки

Я опять перезаписал колонки!

In [137]:
# Смотрим типы данных датасета
dtypes = dataset.dtypes
dtypes

poster               object
title                object
certificate          object
runtime              object
genre                object
rating              float64
about                object
director             object
stars                object
votes                object
gross_earn           object
runtime_clear         int64
gross_earn_clear    float64
dtype: object

In [140]:
# Нам нужны нечисловые колонки, а это получается строки
# Еще вариант написать dtypes[ (dtypes != float) & (dtypes != int) ]
num_dtypes = dtypes[dtypes == object]
num_dtypes

poster         object
title          object
certificate    object
runtime        object
genre          object
about          object
director       object
stars          object
votes          object
gross_earn     object
dtype: object

In [141]:
# Смотрим индексы и сохраняем их в переменную
new_columns = num_dtypes.index
new_columns

Index(['poster', 'title', 'certificate', 'runtime', 'genre', 'about',
       'director', 'stars', 'votes', 'gross_earn'],
      dtype='object')

In [142]:
# Применяем фильтрацию к датасету, выводя по индексам все колонки, где тип строковый данных (object в pandas)
filtered_dataset_6 = dataset[new_columns]
filtered_dataset_6.head()
# Напомню, что в первой части работы (эта третья), мы редактировали данные, переводя из строкового типа данных в числовой. Теперь мы убрали эти колонки.

poster  \
0  https://m.media-amazon.com/images/S/sash/4Fyxw...   
1  https://m.media-amazon.com/images/S/sash/4Fyxw...   
2  https://m.media-amazon.com/images/S/sash/4Fyxw...   
3  https://m.media-amazon.com/images/S/sash/4Fyxw...   
4  https://m.media-amazon.com/images/S/sash/4Fyxw...   

                      title certificate  runtime                      genre  \
0  The Shawshank Redemption          15  142 min                      Drama   
1            Hababam Sinifi         12A   87 min              Comedy, Drama   
2             The Godfather           X  175 min               Crime, Drama   
3    The Godfather: Part II           X  202 min               Crime, Drama   
4          Schindler's List          15  195 min  Biography, Drama, History   

                                               about              director  \
0  Two imprisoned men bond over a number of years...        Frank Darabont   
1  Lazy, uneducated students share a very close b...         Ertem Egilmez   
2  The aging patriarch of an organized crime dyna...  Francis Ford Coppola   
3  The early life and career of Vito Corleone in ...  Francis Ford Coppola   
4  In German-occupied Poland during World War II,...      Steven Spielberg   

                                               stars      votes gross_earn  
0  ('Tim Robbins',), ('Morgan Freeman',), ('Bob G...  26,26,905    $28.34M  
1  ('Kemal Sunal',), ('Münir Özkul',), ('Halit Ak...     40,492        NaN  
2  ('Marlon Brando',), ('Al Pacino',), ('James Ca...  18,19,641   $134.97M  
3  ('Al Pacino',), ('Robert De Niro',), ('Robert ...  12,49,182    $57.30M  
4  ('Liam Neeson',), ('Ralph Fiennes',), ('Ben Ki...  13,33,407    $96.90M

## 8. Группировка

### *8.1. certificate - gross_earn_clear*

**Описание:** сгруппируйте датасет по классам фильмов и рассчитайте по ним среднее значение доходов с фильмов

Сгруппируйте исходный датасет dataset по признаку certificate с помощью метода groupby и сохраните результат в переменную groups

In [143]:
groups = dataset.groupby('certificate')
groups

Рассчитайте среднее значение по признаку gross_earn_clear с помощью метода mean() по сгруппированному объекту. Результаты сохраните в переменную groups_mean_earn

In [155]:
groups_mean_earn = groups['gross_earn_clear'].mean()
groups_mean_earn

certificate
(Banned)           NaN
12           60.113048
12A          77.310925
15           33.451798
18           26.607200
A            37.906190
AA           38.855769
Not Rated     3.830000
PG           64.011360
PG-13        11.922222
R             3.487273
Rejected      1.060000
U            85.989083
UA           71.939091
X            23.783846
Name: gross_earn_clear, dtype: float64

Для удобства чтения полученных значений округлите средние значения до двух знаков после запятой с помощью метода apply(), применив формат "{0:.2f}".format

In [156]:
groups_mean_earn = groups_mean_earn.apply("{0:.2f}".format)
groups_mean_earn

certificate
(Banned)       nan
12           60.11
12A          77.31
15           33.45
18           26.61
A            37.91
AA           38.86
Not Rated     3.83
PG           64.01
PG-13        11.92
R             3.49
Rejected      1.06
U            85.99
UA           71.94
X            23.78
Name: gross_earn_clear, dtype: object

### *8.2. certificate - rating - gross_earn_clear*

**Описание:** сгруппируйте датасет по классам фильмов и по их рейтингу и рассчитайте по ним медианное значение доходов с фильмов

Сгруппируйте исходный датасет dataset по признакам certificate и rating с помощью метода groupby и сохраните результат в переменную groups_2

In [162]:
groups_2 = dataset.groupby(['certificate', 'rating'])
groups_2

Рассчитайте среднее значение по признаку gross_earn_clear с помощью метода median() по сгруппированному объекту. Результаты сохраните в переменную groups_mean_earn_2


In [166]:
groups_mean_earn_2 = groups_2['gross_earn_clear'].median()
groups_mean_earn_2

certificate  rating
(Banned)     6.8           NaN
12           2.5        21.470
             3.0        20.760
             3.5        10.980
             3.6        15.220
                        ...   
X            8.5        81.185
             8.6           NaN
             8.8         6.100
             9.0        57.300
             9.2       134.970
Name: gross_earn_clear, Length: 451, dtype: float64

Вы справились!

### **8.3. certificate - runtime_clear*

По аналогии выведите информацию о продолжительности фильмов в зависимости от их класса.

In [163]:
# Группируем данные по сертификату.
groups = dataset.groupby('certificate')
groups

In [167]:
# Смотрим  медиану колонки runtime_clear по каждому классу certificate
groups_runtime = groups['runtime_clear'].mean()
groups_runtime

certificate
(Banned)      91.000000
12           109.982014
12A          115.449239
15           109.385241
18           109.033384
A            114.397849
AA           114.949153
Not Rated    103.000000
PG           110.058632
PG-13         99.636364
R            134.500000
Rejected      86.200000
U            102.444751
UA           117.636364
X            112.410448
Name: runtime_clear, dtype: float64

In [168]:
# Форматируем runtime_clear до двух знаков после запятой
groups_runtime = groups_runtime.apply("{0:.2f}".format)
groups_runtime

certificate
(Banned)      91.00
12           109.98
12A          115.45
15           109.39
18           109.03
A            114.40
AA           114.95
Not Rated    103.00
PG           110.06
PG-13         99.64
R            134.50
Rejected      86.20
U            102.44
UA           117.64
X            112.41
Name: runtime_clear, dtype: object

### **8.4. certificate - rating - runtime_clear*

По аналогии выведите информацию о продолжительности фильмов в зависимости от их класса и рейтинга.

In [169]:
# Группируем датасет по классу и рейтингу
groups_2 = dataset.groupby(['certificate', 'rating'])
groups_2

In [170]:
# Смотрим медиану продолжительности по каждому классу и существующим в нем рейтингам
groups_runtime_2 = groups_2['runtime_clear'].median()
groups_runtime_2

certificate  rating
(Banned)     6.8        91.0
12           2.5       118.0
             3.0        89.0
             3.5       107.0
             3.6       107.0
                       ...  
X            8.5       132.0
             8.6       133.0
             8.8       148.0
             9.0       202.0
             9.2       175.0
Name: runtime_clear, Length: 451, dtype: float64

**Поздравляем! Часть 3 задания по модулю EDA выполнена!**

**Вы завершили выполнение тренировочного задания!**

**Не забудьте изучить тему по созданию наглядных графиков!**

**Удачи на курсе!**